In [6]:
import torch

labels = torch.tensor([-100, -100, -100, -100, -100, 23, 42, -100, 2, 3, 4, 5, 1])
# labels = torch.tensor([-100, -100, -100, -100, -100, 23, 42])
mask = labels != -100

print(mask)

tensor([False, False, False, False, False,  True,  True, False,  True,  True,
         True,  True,  True])


In [7]:
weights = torch.zeros_like(labels, dtype=torch.float32)
print(weights)

group_ids = torch.zeros_like(labels).int()
print(group_ids)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=torch.int32)


In [8]:
gid = 0
for j in range(1, labels.size(0)):
    if mask[j] and not mask[j-1]:
        gid += 1
    group_ids[j] = gid if mask[j] else 0

print(group_ids)


tensor([0, 0, 0, 0, 0, 1, 1, 0, 2, 2, 2, 2, 2], dtype=torch.int32)


In [9]:
counts = torch.bincount(group_ids[mask])
print(counts)


tensor([0, 2, 5])


In [10]:
print(counts[group_ids[mask]])

weights[mask] = 1.0 / counts[group_ids[mask]]

print(weights)

tensor([2, 2, 5, 5, 5, 5, 5])
tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.5000, 0.5000, 0.0000, 0.2000,
        0.2000, 0.2000, 0.2000, 0.2000])


In [1]:
import torch

row = torch.tensor([-100, -100, -100, -100, -100, 23, 42, -100, 2, 3, 4, 5, 1])
# row = torch.tensor([-100, -100, -100, -100, -100, 23, 42])
mask  = row != -100  

print(mask)

tensor([False, False, False, False, False,  True,  True, False,  True,  True,
         True,  True,  True])


In [2]:
weights = torch.zeros_like(row, dtype=torch.float32)

In [3]:
gids  = torch.zeros_like(row).int()       # 片段编号
        
# 为每个 token 分配一个"段 ID"
gid   = 0
for k in range(1, row.size(0)):
    if mask[k] and not mask[k-1]:         # -100 → 有效，开始新片段
        gid += 1
    gids[k] = gid if mask[k] else 0

print(gids)

tensor([0, 0, 0, 0, 0, 1, 1, 0, 2, 2, 2, 2, 2], dtype=torch.int32)


In [4]:
counts = torch.bincount(gids[mask])       # 每片段 token 数
print(counts)


weights[mask] = 1.0 / counts[gids[mask]]
print(weights)

tensor([0, 2, 5])
tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.5000, 0.5000, 0.0000, 0.2000,
        0.2000, 0.2000, 0.2000, 0.2000])


In [12]:
tmp = [2, 3, 1, 5, 7]


for k in range(0, len(tmp)):
    print(k)


print(tmp[-1])

0
1
2
3
4
7


In [1]:
a = 0.5109832882881165
b = 0.2616356313228607

print(b*2 - a)

0.01228797435760498


In [1]:
num = [27.19, 26.21, 27.38, 27.25]

print(sum(num)/len(num))

27.0075
